#!/usr/bin/env sh

# Simple deployment script for GitHub pages.

BUILD_DIR="$1"
TARGET_DIR="$2"

if [[ "$BUILD_DIR" = "" ]] then
	echo "error: build directory not specified"
	exit 1
fi

if [[ "$TARGET_DIR" = "" ]] then
	TARGET_DIR=`pwd`
	echo "notice: target directory set to current dir"
fi

echo -e "Deploying build\n\tfrom:\t$BUILD_DIR\n\tto:\t$TARGET_DIR"

rm -r $TARGET_DIR/index.html $TARGET_DIR/assets

cp -r $BUILD_DIR/index.html "$TARGET_DIR/index.html"
cp -r $BUILD_DIR/assets "$TARGET_DIR/assets"

REV=$(cat $TARGET_DIR/.build.revision)
REV_NEXT=$(expr $REV + 1)

echo "Current revision is: $REV"
echo "Next revision is: $REV_NEXT"

echo "$REV_NEXT" > .build.revision

git add .build.revision index.html assets
git status -s

read -p "Commit changes? (y/n): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

git commit -m "release r$REV_NEXT"
git log -n 1
git tag "r$REV_NEXT"

echo "Diff stats:"
git diff --stat HEAD..HEAD~1
echo "Revision tag: "
git tag -l "r$REV_NEXT"

read -p "Push to production? (y/n): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

git push origin && git push origin tag "r$REV_NEXT"
